[general]
import = [
  "~/.config/alacritty/themes/themes/seoul256-light-mod.toml",
  "~/.config/alacritty/local.toml",
]
live_config_reload = true

[window]
startup_mode  = "Windowed"
dynamic_title = true

[scrolling]
history = 0

[cursor]
unfocused_hollow = true

[[hints.enabled]]
command         = "open"
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
hyperlinks      = true
post_processing = true
mouse           = { enabled = true, mods = "None" }
binding         = { key = "O", mods = "Control|Shift" }

[cursor.style]
shape = "Block"
