# terminal.sexy - seoul256 light
# converted from https://github.com/junegunn/seoul256.vim
[colors.seoul256-light.primary]
background = "0xdadada"
foreground = "0x4e4e4e"

[colors.seoul256-light.normal]
black = "0x4e4e4e"
red = "0xaf5f5f"
green = "0x5f885f"
yellow = "0xaf8760"
blue = "0x5f87ae"
magenta = "0x875f87"
cyan = "0x5f8787"
white = "0xe4e4e4"

[colors.seoul256-light.bright]
black = "0x3a3a3a"
red = "0x870100"
green = "0x005f00"
yellow = "0xd8865f"
blue = "0x0087af"
magenta = "0x87025f"
cyan = "0x008787"
white = "0xeeeeee"

