# https://github.com/uga-rosa/denippet.vim/blob/main/doc/denippet.txt
# placeholder-transform examples
# "${TM_FILENAME/[\\.]/_/}"		jexample-123_456-TEST.js	Replace the first . with _
# "${TM_FILENAME/[\\.-]/_/g}"		example_123_456_TEST_js		Replace each . or - with _
# "${TM_FILENAME/(.*)/${1:/upcase}/}"	EXAMPLE-123.456-TEST.JS		Change to all uppercase
# "${TM_FILENAME/[^0-9^a-z]//gi}"		example123456TESTjs		Remove non-alphanumeric characters

[snippet]
prefix = ["${1:prefix}"]
body = ""
description = "${2:optional_description_field}"
