# ~/.config/twm/twm.yaml

search_paths:  # directories we should begin searching for workspaces in. i just use home. shell expansion is supported
    - "~"      # default: ["~"]
    - "/mnt/arboghast/Workspace"

exclude_path_components:  # search branches will be pruned the path being explored contains any of these components
  - .cache
  - .direnv
  - .git
  - node_modules
  - target
  - venv

max_search_depth: 5  # how deep we should search for workspaces (default: 3)
session_name_path_components: 3    # how many parts of the workspace path to use in generating the session name by default
                                   # if you attempt to open two separate workspaces that would generate the same session name,
                                   # this value will be incremented until a unique session name is found

workspace_definitions:             # our list of workspaces, each with different properties
    - name: python                 # they all have to be named
      has_any_file:                # if any file matches this list, we consider it a match, since its "has_any_file"
        - requirements.txt         # more complex matching isn't implemented currently
        - setup.py
        - pyproject.toml
        - Pipfile
      default_layout: python-dev   # the hierarchy for how a layout gets chosen is user opts to select manually > local layout > default for workspace type

        #    - name: node                   # the order of these definitions matters - if a directory matches multiple, the first one wins
        #      has_any_file:
        #        - package.json
        #        - yarn.lock
        #        - .nvmrc
        #      default_layout: node-dev

        #- name: rust
        #  has_any_file:
        #    - Cargo.toml
        #    - Cargo.lock
        #  default_layout: rust-dev

    - name: k3s-sbc
      has_any_file:
        - tbd.toml
        - main.tf
        - providers.tf
      default_layout: k3s

    - name: other
      has_any_file:
        - .git
        - flake.nix
        - .twm.yaml

layouts:                           # our list of layouts just have names and a list of commands. the command get sent directly with tmux send-keys
    - name: python-dev             # i chose not to use any custom configuration becuase that would be a lot of work to basically maintain a subset of possible functionality
      # TODO FIX FOR ME
      commands:
        - tmux split-window -v
        - tmux resize-pane -D 20
        - tmux split-window -h
          #        - tmux send-keys -t 0 'nvim .' C-m

          #    - name: rust-dev
          #      commands:
          #        - tmux split-window -h
          #        - tmux resize-pane -x 80
          #        - tmux select-pane -t 0
          #        - tmux send-keys -t 1 'cargo watch -x test -x run' C-m
          #        - nvim .

    - name: k3s
      # TODO SETUP MOSH SSH_CONFIG STUFF
      commands:
        - tmux new-window
        - tmux rename-window -t 2 "sbcs"
        - tmux split-window -v
        - tmux split-window -h
        - tmux split-window -h
        - tmux select-pane -t 2
        - tmux resize-pane -x 33%
        - tmux select-pane -t 3
        - tmux resize-pane -x 33%
        - tmux select-pane -t 1
        - tmux split-window -h
        - tmux send-keys -t 1 'me mosh hartigan@arnold' C-m
        - tmux send-keys -t 2 'me mosh hartigan@bernard' C-m
          #        - tmux send-keys -t 3 'me mosh hartigan@ford' C-m
        - tmux send-keys -t 4 'me mosh hartigan@dolores' C-m
        - tmux send-keys -t 5 'me mosh hartigan@maeve' C-m
