[tools]
"aqua:atuinsh/atuin"       = "latest"
"cargo:du-dust"            = "latest"
"aqua:getsops/sops"        = "latest"
"cargo:atac"               = "latest"
"cargo:jsongrep"           = "latest"
"cargo:twm"                = "latest"
"cargo:tlrc"               = "latest"
duf                        = "latest"
fzf                        = "latest"
"github:dandavison/delta"  = "latest"
"github:SuperCuber/dotter" = "latest"
"github:tamasfe/taplo"     = "latest"
stern                      = "latest"
tree-sitter                = "latest"
ty                         = "latest"
usage                      = "latest"
zoxide                     = "latest"

[plugins]
